### ISSUE TITLE
splitPopulationFile splitting population into wrong number of files

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.Core#757] opened 2020-03-27 06:22 UTC
Example here: should produce four new population files, but only three created
[splitpoptest.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/4391858/splitpoptest.zip)

**Comment by msevestre** [comment] 2020-03-27 16:44
In fact this is by design I believe
@Yuri05 Can you confirm that this was the idea when you implemented it?

e.g. We find the max size of a bucket by dividing the number of sim by the number of cors

in your case 5/4 => the max size is 2
So each core will get up to 2 individuals

Core 1 : 2
Core 2: 2
Core 3: 1
Core 4: nothing

So in this case, Core 4 will be in fact left unused

see `DataSplitter`

```
      private int getNumberOfSimulationsPerCore()
      {
         int numberOfJobs = NumberOfIndividuals;

         //cannot use more cores than jobs
         int numberOfCoresToUse = Math.Min(numberOfJobs, _numberOfCores);

         int rowsPerCore = numberOfJobs / numberOfCoresToUse;

         if (rowsPerCore * _numberOfCores < numberOfJobs)
            rowsPerCore += 1;

         return rowsPerCore;
      }
```

**Comment by Yuri05** [comment] 2020-03-27 17:04
Nothing to do here from my point of view. Load balancing behaviour cannot be improved if we change this.
E.g. in your example above it does not matter if it's 2+2+1+0 or 1+1+1+2 or whatever else. We would have at least one core with 2 simulations

**Comment by msevestre** [comment] 2020-03-27 17:08
That's not the problem I think. Here we have one core that's not being used
with the current implementation

**Comment by Yuri05** [comment] 2020-03-27 17:18
If for some reason (which I don't understand) having empty cores is a problem: splitting routine could calculate how many cores will be effectively used and return this value to the Reporting Engine. 
RE would than allocate exactly this number of Cores (and not the Core-amount entered by user)

**Comment by msevestre** [comment] 2020-03-27 17:21
if you don't see any problem, then this is by design 

FYI @abdullahhamadeh . The number of cores will be the MAXIMUM number of cores used.

**Closed by msevestre** 2020-03-27 17:21 UTC
