### ISSUE TITLE
Exception when starting importer and closing the view right away by clicking on the X 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#940] opened 2021-03-30 19:17 UTC
Application:
PK-Sim® 10.0.0

Value cannot be null.
Parameter name: key

Stack trace:
```
at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Core.Domain.Project.AddImporterConfiguration(ImporterConfiguration configurationToAdd)
   at OSPSuite.Core.Commands.AddImporterConfigurationToProjectCommand.ExecuteWith(IOSPSuiteExecutionContext context)
   at OSPSuite.Core.Commands.OSPSuiteCommand`1.Execute(TContext context)
   at OSPSuite.Core.Commands.Core.CommandExtensions.Run[T,ExecutionContext](T commandToExecute, ExecutionContext context)
   at OSPSuite.Core.Domain.Services.ObservedDataTask.AddImporterConfigurationToProject(ImporterConfiguration configuration)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.addObservedData(Func`1 importConfiguration, Compound compound, Boolean allowCompoundNameEdit) in C:\projects\PK-Sim\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 205
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProjectForCompound(Compound compound) in C:\projects\PK-Sim\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 142
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProject() in C:\projects\PK-Sim\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 64
   at PKSim.Presentation.UICommands.ImportConcentrationDataCommand.Execute() in C:\projects\PK-Sim\src\PKSim.Presentation\UICommands\ImportConcentrationDataCommand.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by georgeDaskalakis** [comment] 2021-03-31 10:31
This is fixed on branch "importer-corrections" on PK-Sim. I have tried closing the window on various cases (included right when starting the importer) but could not reproduce.

**Closed** 2021-05-07 15:25 UTC
Labels: Importer-Redesign, should have been closed, type: bug
