### ISSUE TITLE
Error when selecting a neighbor when...

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2354] opened 2024-10-29 17:56 UTC
Somehow related to https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2345 and https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2353

AFTER showing the diagram, switch back to the tree view and select "Endometrium":

Application:
MoBi® 12.0.361

Selected objects must belong to the view or its document

Stack trace:
```
at Northwoods.Go.GoSelection.Add(GoObject obj)
   at OSPSuite.UI.Views.Diagram.BaseDiagramView.Select[T](T node)
   at MoBi.Presentation.Presenter.BaseDiagram.MoBiBaseDiagramPresenter`3.Handle(EntitySelectedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by rwmcintosh** [comment] 2024-11-04 14:43
This is caused by #2353 I'm going to optimistically close it. 

It does happen if you get the error in #2353 first, but once that error is fixed, this one won't occur.

**Closed by rwmcintosh** 2024-11-04 14:43 UTC
Labels: type: bug
