### ISSUE TITLE
Inconsistent `runSimulationBatches` and `runSimulation` results

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.Core#1646] opened 2022-06-25 14:17 UTC
[test-simbatch-script-pkml.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/8984909/test-simbatch-script-pkml.zip)

![image](https://user-images.githubusercontent.com/18409098/175777492-a430e6d9-5229-4cc0-94be-956dbfad136b.png)

MoBi reproduces the `runSimulation` result, and it is more in line with what I think is the right order of magnitude.

**Comment by msevestre** [comment] 2022-06-27 01:55
FYI @abdelr @Yuri05 
We should look into this asap

**Comment by msevestre** [comment] 2022-06-27 03:13
I can reproduce in the .NET code 
![image](https://user-images.githubusercontent.com/1041237/175853117-4146391d-79b0-4722-9644-c5fdbeb11cc7.png)

**Comment by msevestre** [comment] 2022-06-27 03:13
Thanks @abdullahhamadeh for providing a example to reproduce

**Comment by msevestre** [comment] 2022-06-27 03:20
Note: This is specific to this simulation. @abdullahhamadeh had reported a similar bugs a while back and we had a test for this testing exactly the same behavior. Is there something special about this observer?

**Comment by abdullahhamadeh** [comment] 2022-06-27 03:35
Thanks for checking this @msevestre. I guess you may consider it special in the sense that it observes the value of a parameter in the molecule building block and not a time-varying quantity like a molecule amount or concentration.  Other than that I don't think it is special.

Btw the error is sensitive to the value of the input parameter `parVals`, which sets the parameter `DERMAL_APPLICATION_AREA|skin_compartment|r2`.  If `parVals <- c(6e-09)` instead of `parVals <- c(5e-09)` the results are consistent.

**Comment by msevestre** [comment] 2022-06-27 03:55
@Yuri05 I think this is a SimModel error. I have exported both simulations to Matlab using the `ExportToCode` method 

## scenario 1

I only vary a parameter such as the Volume by setting it to the same value as it is in the simulation 
` "DERMAL_APPLICATION_AREA|Volume" = 1`

The export of the simulations both in Formula and values are identical (BTW I do not think that the Values mode works as it is the exact same output as in the Formula mode)
```
         _simModelSimulation.ExportToCode(@"C:\tests\v12\1646\Batch2\Values", CodeExportLanguage.Matlab, CodeExportMode.Values, "S1");
         _simModelSimulation.ExportToCode(@"C:\tests\v12\1646\Batch2\Formula", CodeExportLanguage.Matlab, CodeExportMode.Formula, "S2");
```

## scenario 2
I only vary this one parameter `DERMAL_APPLICATION_AREA|skin_compartment|r2` by setting the value 5e-09

In this case, the `ExportToCode` are different! There is a difference in 5 parameters

Using the SimulationRunner (same as mobi), I observe the following parameters values

| ID | Value | Path|
| - | - | - |
|P_658| 2.929535149472482e-09 | veh_inf_aq_no_pt_standard_skin_simulation_v14-DERMAL_APPLICATION_AREA-skin_compartment-epsilon3
|P_1351|1.054342554027741| veh_inf_aq_no_pt_standard_skin_simulation_v14-permeant-lambda2|
|P_1363|-1.92118799184607e-05| veh_inf_aq_no_pt_standard_skin_simulation_v14-permeant-H_lambda_lt_0p4|
|P_1364|NaN| veh_inf_aq_no_pt_standard_skin_simulation_v14-permeant-H_lambda_gt_0p4|
|P_1371|NaN| veh_inf_aq_no_pt_standard_skin_simulation_v14-permeant-H|

Using the batch runner (wrong values)

| ID | Value | Path|
| - | - | - |
|P_658|((P_515^2)*117181405.9788993)| veh_inf_aq_no_pt_standard_skin_simulation_v14-DERMAL_APPLICATION_AREA-skin_compartment-epsilon3|
|P_1351|(5.271712770138704e-09/P_515)| veh_inf_aq_no_pt_standard_skin_simulation_v14-permeant-lambda2|
|P_1363|(((1-P_1351)^2)*(1+((-2.104)*P_1351)+(2.09*(P_1351^3))+((-0.95)*(P_1351^5))))| |veh_inf_aq_no_pt_standard_skin_simulation_v14-permeant-H_lambda_lt_0p4
|P_1364|((((1-P_1351)^2)*18.84955592153876)/((31.4*((1-P_1351)^(-2.5))*(1+((-1.217)*(1-P_1351))+(1.534*((1-P_1351)^2))))+(-22.51)+((-5.612)*(P_1351^1))+((-0.3363)*(P_1351^2))+((-1.216)*(P_1351^3))+(1.647*(P_1351^4))))| veh_inf_aq_no_pt_standard_skin_simulation_v14-permeant-H_lambda_gt_0p4|
|P_1371|(IIf((P_1351 <= 0.4),P_1363,P_1364))| veh_inf_aq_no_pt_standard_skin_simulation_v14-permeant-H|


@Yuri05 Any reason why those parameters would not be simplified ? Or why would they be constant in once case and a formula in the other...

**Comment by msevestre** [comment] 2022-06-27 03:58
note that in scenario 1, the formula of batch case are simplified. So somehow, some simplification/calculation of formula is not working as expected

**Comment by Yuri05** [comment] 2022-06-27 10:59
@msevestre 

>The export of the simulations both in Formula and values are identical (BTW I do not think that the Values mode works as it is the exact same output as in the Formula mode)

         _simModelSimulation.ExportToCode(@"C:\tests\v12\1646\Batch2\Values", CodeExportLanguage.Matlab, CodeExportMode.Values, "S1");
         _simModelSimulation.ExportToCode(@"C:\tests\v12\1646\Batch2\Formula", CodeExportLanguage.Matlab, CodeExportMode.Formula, "S2");

If you take **the same** SimModel-simulation (which seems to be the case in the code above) and export it 2 times (values-mode and formula-mode) then indeed the result will be the same.
Because the differentiation is made before the simulation finalization. Once finalized (which happens in the ExportToMatlab function if it's not already the case) - there will be no difference.
https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/99d0c71cb8b8405124174c7d90121ad8d9d0771b/src/OSPSuite.SimModelNative/src/MatlabODEExporter.cpp#L64-L76

This export was designed to be called from the **ModelCoreSimulation** (where SimModel-Export is created on the fly every time)

**Comment by Yuri05** [comment] 2022-06-27 11:27
[06_SimulationBatch.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/8991306/06_SimulationBatch.zip)
OK, I imported the pkml in MoBi and calculated: same results as in runSimulation_results screenshot by @abdullahhamadeh 
![grafik](https://user-images.githubusercontent.com/25061876/175929801-11b03139-927d-4761-91a8-a9a19b690429.png)

Then sent the simulation to PK-Sim for population simulation, allocated 10 individuals **without any parameter variation**
and calculated. Should produce the same result as in MoBi - but it doesn't:

![grafik](https://user-images.githubusercontent.com/25061876/175930274-58f14925-eb4a-487b-987d-f7cc4f846215.png)

If I set the parameter **.../r2** as variable (in fact letting its value unchanged) - the result in PK-Sim does not change
![grafik](https://user-images.githubusercontent.com/25061876/175930480-ef412b8f-7a1c-4e01-b81b-cf1df602e755.png)

So even without any parameter variation there is already something wrong here...

**Comment by Yuri05** [comment] 2022-06-27 11:50
[P2.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/8991628/P2.zip)
OK, if in MoBi I **recreate** the simulation from building blocks - I get the same result as in PK-Sim

![grafik](https://user-images.githubusercontent.com/25061876/175933909-ca9de73d-f6e2-4be0-bebf-194a455dda0f.png)

So somehow the simulation **ssss_0.pkml** from the original post by @abdullahhamadeh is corrupted.
Comparing the imported simulation and the simulation recreated from the building blocks of the imported simulation: there are a lot of differences.
![grafik](https://user-images.githubusercontent.com/25061876/175934238-ed29fc54-479e-4907-8bfd-64b792180d36.png)

I think it has something to do with the the saving of simulation (pkml) with modified parameters from R.
Those modified parameters are set either in PSV or in the simulation - but not in both (even though the simulation state is shown as green when importing).

**Comment by Yuri05** [comment] 2022-06-27 11:54
Here:
PSV: 
![grafik](https://user-images.githubusercontent.com/25061876/175935018-e8f14fa4-b27b-4fd1-90e7-e8b21c9d6a11.png)

Simulation:
![grafik](https://user-images.githubusercontent.com/25061876/175935245-840045c6-d090-40f9-bbc9-543a3c0902a7.png)

**Comment by Yuri05** [comment] 2022-06-27 11:56
relates to https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/398

**Comment by Yuri05** [comment] 2022-06-27 14:23
@msevestre @abdullahhamadeh Can you reproduce the issue with a **regular** simulation? E.g. with the simulation **S2** from the project attached here (https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1646#issuecomment-1167254905)?
This kind of issues is pretty hard to debug, so I would like to exclude all other problems as far as possible.

**Comment by abdullahhamadeh** [comment] 2022-06-27 14:38
![image](https://user-images.githubusercontent.com/18409098/175966914-e4d69e91-f6af-4062-8512-1301dc4e67c4.png)
[S2example.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/8992920/S2example.zip)

Again the same issue occurs with S2 when `r2` is adjusted to value that yields a `NaN`, in this case `r2 = 4.6E-09` gives the `NaN`.

**Comment by Yuri05** [comment] 2022-06-30 10:57
Interesting issue :)
I can reproduce it purely in MoBi, if I create a second simulation where I define `r2 `by e.g. the formula:
`r2 = Time < 999999 ? 4.6E-9 : 1.6`
Thus it remains const=0.46 nm during the simulation, but from the solver point of view it is time dependent and cannot be simplified. Then I can reproduce the differences between the original simulation (r2=const=0.46 nm) and this one.
[P1_02.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/9019115/P1_02.zip)

For your example I can track the differences down to the differences in `permeant|sigma3`, which is plotted as `const = 0` for the simulation S2 (which is clearly wrong) and as `const = NaN` for the simulation with r2 defined by formula.

```
Parameter: S2|permeant|sigma3
	Value: NaN
	Formula: epsilon3*D_aq*H/(D_cor_free*K_cor_w_free)
		epsilon3: S2|DERMAL_APPLICATION_AREA|skin_compartment|epsilon3(2.47955855051351E-09)
		D_aq: S2|permeant|D_aq(3.55741834500176E-06 [dm²/min])
		H: S2|permeant|H(NaN)
		D_cor_free: S2|permeant|D_cor_free(5.48891220824735E-07 [dm²/min])
		K_cor_w_free: S2|permeant|K_cor_w_free(0.222551205186412)
```

`sigma3 `depends on one NaN-parameter (`permeant|H`) which is plotted as NaN by both simulations.
So this is one point I need to investigate further.

In general the problems originate from NaN-values. E.g. NaN are not properly catched in the conditional statements.
E.g. in the example below I define `p1 = 0/0 ` and `p2 = p1 > 0 ? 1 : 999`.
Because p1 is NaN p2 should be NaN as well - however it evaluates to 999 (meaning that `NaN >0` evaluates to `false`)
![grafik](https://user-images.githubusercontent.com/25061876/176659177-f9b99706-3fa3-4c5a-8858-fe0f22c5966a.png)

Will create an Issue for this

In the skin model we have then e.g. parameters like below
```
Parameter: S2|permeant|P_comp_skin_inf_w
	Value: 0.000164585197259598 [dm/min]
	Formula: 1/(  (P_sc_par > 0 ? (1/P_sc_par):0) + (P_sc_np > 0 ? (1/P_sc_np):0) + (P_ed_par > 0 ? (1/P_ed_par):0) + (P_ed_np > 0 ? (1/P_ed_np):0) + (P_de_par > 0 ? (1/P_de_par):0) + (P_de_np > 0 ? (1/P_de_np):0)  )
		P_sc_par: S2|permeant|permeability_parallel_SC(NaN [dm/min])
		P_sc_np: S2|permeant|permeability_nonparallel_SC(0 [dm/min])
		P_ed_par: S2|permeant|permeability_parallel_ED(0.00080206020427246 [dm/min])
		P_ed_np: S2|permeant|permeability_nonparallel_ED(0 [dm/min])
		P_de_par: S2|permeant|permeability_parallel_DE(0.000299276195624052 [dm/min])
		P_de_np: S2|permeant|permeability_nonparallel_DE(0.000672180201012381 [dm/min])
```
The value should be NaN - but evaluates to some (wrong) finite value here.

So in https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1646#issuecomment-1167437533 **both results are wrong and should be NaN**

**Comment by msevestre** [comment] 2022-06-30 12:33
This is so messed up. 
Now the formula above can clearly be 1/0. Isn't it something that should be avoided?

**Comment by Yuri05** [comment] 2022-06-30 12:59
>Now the formula above can clearly be 1/0. Isn't it something that should be avoided? 

Depends. 1/0 is Inf, and in some cases it can be handled. 
We even have situations where **default** parameter values are Infinity :wink: 
<img width="500" src="https://user-images.githubusercontent.com/25061876/176680985-6f90a838-8916-418f-a951-81ffb88d9104.png">

NaN should be avoided at any rate.
Maybe we can add an **on-demand** NaN check for parameter values in MoBi (on simulation level).

**Comment by msevestre** [comment] 2022-06-30 13:18
Right of course. So how can the formula above be NaN  if it is at most 1/0 ? This is so interesting :)

**Comment by abdullahhamadeh** [comment] 2022-06-30 14:27
Thanks Juri.  Yes that's exactly right and that is the modification I made to make it work in this case.  If this error occurs again, should we expect all outputs to be NaN?

**Comment by Yuri05** [comment] 2022-06-30 14:37
@abdullahhamadeh It depends. If any equation of the RHS of the ODE becomes NaN due to input NaN parameters - the system will quit with the error "RHS is not finite" in any case.
If it is used just in one or more observers - to be discussed. At the moment (after the SimModel bugs discussed above are fixed) the corresponding observers would be just produced as const NaN. That's a question if this case should be catched as well (so that the simulation stops as soon as any observer becomes NaN) or if we should allow it.

**Comment by PavelBal** [comment] 2022-09-08 10:08
I am a bit lost in the discussion. Any progress or consensus on how to proceed?

**Comment by Yuri05** [comment] 2022-09-09 09:17
@PavelBal I think we have an agreement, yes:
1) (must) fix the issue https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/issues/148
2) (nice to have) introduce **on-demand** check of non-finite (NaN or +- :infinity: ) parameter values in MoBi

**Comment by PavelBal** [comment] 2022-09-09 09:27
2. it would be a helpful feature indeed. I would also expose this to R. In this case it would be an issue for Core, right?

**Comment by msevestre** [comment] 2022-09-09 11:13
I don't understand what you mean with #2.'can you elaborate @Yuri05

**Comment by Yuri05** [comment] 2022-09-09 13:09
> I don't understand what you mean with #2.'can you elaborate @Yuri05

MoBi could go through all parameters of the simulation and check, if their (initial) value is finite or not. And if at least one such parameter is found - produce warning (or error) with the list of problematic parameters.
I would do it on demand only, because not all parameters are effectively used in the model, and even if a parameter is used - it migth affect e.g. only an **observer** - which should not prevent the simulation from running (as discussed above).

So I would either introduce additional button, which would trigger this check at any time, or a new option "Check initial parameter values when starting a simulation" (false as per default).

**Comment by PavelBal** [comment] 2022-09-12 10:04
Vote for button or a simulation context menu.

**Comment by PavelBal** [comment] 2022-10-11 13:54
Must be fixed in SimModel

**Closed by PavelBal** 2022-10-11 13:54 UTC
Labels: type: bug, prio: high
